from cgitb import text
import tkinter as tk
from math import sin, cos, tan, radians,log, log10, sqrt, asin, acos, atan, degrees
from tkinter.font import BOLD
calculation=""
def calculation_string(num):
    global calculation
    calculation +=str(num)
    text_display.delete(0,'end')
    text_display.insert(tk.END,calculation)
def evaluate_cal_string():
    global calculation
    calculation=str(eval(calculation))
    text_display.delete(0,tk.END)
    text_display.insert(tk.END,calculation)
def delete():
    len_cal=len(text_display.get())
    text_display.delete(len_cal-1,tk.END)
def clear():
    global calculation
    calculation=""
    text_display.delete(0,tk.END)
root=tk.Tk()
root.configure(bg='black')
root.title("Simple Scientific Calculator")
root.geometry("553x900") 
text_display=tk.Entry(root,width=30,font=('ds-digital',25),borderwidth=5,bg='#5a5a5a')
text_display.grid(columnspan=4)
btn1=tk.Button(root,text='1',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(1))
btn1.grid(row=8,column=0,sticky='WENS')
btn2=tk.Button(root,text='2',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(2))
btn2.grid(row=8,column=1,sticky='WENS')
btn3=tk.Button(root,text='3',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(3))
btn3.grid(row=8,column=2,sticky='WENS')
btn4=tk.Button(root,text='4',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(4))
btn4.grid(row=7,column=0,sticky='WENS')
btn5=tk.Button(root,text='5',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(5))
btn5.grid(row=7,column=1,sticky='WENS')
btn6=tk.Button(root,text='6',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(6))
btn6.grid(row=7,column=2,sticky='WENS')
btn7=tk.Button(root,text='7',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(7))
btn7.grid(row=6,column=0,sticky='WENS')
btn8=tk.Button(root,text='8',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(8))
btn8.grid(row=6,column=1,sticky='WENS')
btn9=tk.Button(root,text='9',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(9))
btn9.grid(row=6,column=2,sticky='WENS')
btn0=tk.Button(root,text='0',font=('ds-digital',10,BOLD),height=3,width=3,bg='gray',fg='white',bd=2,command=lambda: calculation_string(0))
btn0.grid(row=9,column=0,sticky='WENS')
btnpower=tk.Button(root,text='x10^',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("*10**"))
btnpower.grid(row=9,column=2,sticky='WENS')
btnopen=tk.Button(root,text='(',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string('('))
btnopen.grid(row=5,column=0,sticky='WENS')
btnclose=tk.Button(root,text=')',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string(')'))
btnclose.grid(row=5,column=1,sticky='WENS')
btndot=tk.Button(root,text='.',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("."))
btndot.grid(row=9,column=1,sticky='WENS')
btndeq=tk.Button(root,text='=',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=evaluate_cal_string)
btndeq.grid(row=9,column=3,sticky='WENS')
btndel=tk.Button(root,text='Del',font=('ds-digital',10,BOLD),height=5,width=5,bg='#75ff75',fg='white',bd=2,command=delete)
btndel.grid(row=2,column=2,sticky='WENS')
btnclear=tk.Button(root,text='Clear',font=('ds-digital',10,BOLD),height=5,width=5,bg='#75ff75',fg='white',bd=2,command=clear)
btnclear.grid(row=2,column=3,sticky='WENS')
btndplus=tk.Button(root,text='+',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("+"))
btndplus.grid(row=8,column=3,sticky='WENS')
btnminus=tk.Button(root,text='-',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("-"))
btnminus.grid(row=7,column=3,sticky='WENS')
btntimes=tk.Button(root,text='*',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("*"))
btntimes.grid(row=6,column=3,sticky='WENS')
btndvd=tk.Button(root,text='/',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("/"))
btndvd.grid(row=5,column=3,sticky='WENS')
btnexp=tk.Button(root,text='^',font=('ds-digital',10,BOLD),height=5,width=5,bg='gray',fg='white',bd=2,command=lambda: calculation_string("**"))
btnexp.grid(row=5,column=2,sticky='WENS')
btnsin=tk.Button(root,text='sin',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("sin(radians("))
btnsin.grid(row=4,column=0,sticky='WENS')
btncos=tk.Button(root,text='cos',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("cos(radians("))
btncos.grid(row=4,column=1,sticky='WENS')
btntan=tk.Button(root,text='tan',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("tan(radians("))
btntan.grid(row=4,column=2,sticky='WENS')
btnasin=tk.Button(root,text='arcsin',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("asin("))
btnasin.grid(row=3,column=0,sticky='WENS')
btnacos=tk.Button(root,text='arccos',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("acos("))
btnacos.grid(row=3,column=1,sticky='WENS')
btnatan=tk.Button(root,text='arctan',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("atan("))
btnatan.grid(row=3,column=2,sticky='WENS')
btnlog=tk.Button(root,text='log',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("log10("))
btnlog.grid(row=3,column=3,sticky='WENS')
btnln=tk.Button(root,text='ln',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("log("))
btnln.grid(row=4,column=3,sticky='WENS')
btnsqrt=tk.Button(root,text='sqrt',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("sqrt("))
btnsqrt.grid(row=2,column=0,sticky='WENS')
btnDeg=tk.Button(root,text='degrees',font=('ds-digital',10,BOLD),height=5,width=5,bg='#2c2c2c',fg='white',bd=2,command=lambda: calculation_string("degrees("))
btnDeg.grid(row=2,column=1,sticky='WENS')
root.mainloop()